import { PropertyListing } from "@/app/api/properties/route";

export const SAMPLE_PROPERTIES: PropertyListing[] = [
  {
    propertyId: "dubai-marina-lux-1",
    title: "Ultra-Luxury Waterfront Apartment · Dubai Marina",
    description: "Panoramic marina views, floor-to-ceiling windows, and private terrace.",
    propertyType: "Apartment",
    offeringType: "forSale",
    price: 4850000,
    currency: "AED",
    bedrooms: 3,
    bathrooms: 4,
    areaSqft: 2450,
    furnished: "Furnished",
    fullAddress: "Marina Gate Tower, Dubai Marina, Dubai",
    city: "Dubai",
    community: "Dubai Marina",
    agentName: "Ashish Lalwani",
    brokerName: "Vibgyor Real Estate",
    listingUrl: "#contact",
    listedDate: "2026-09-15",
  },
  {
    propertyId: "palm-jumeirah-villa-1",
    title: "Bespoke Beachfront Villa · Palm Jumeirah",
    description: "Direct beach access, infinity pool, and private garden sanctuary.",
    propertyType: "Villa",
    offeringType: "forSale",
    price: 28500000,
    currency: "AED",
    bedrooms: 5,
    bathrooms: 6,
    areaSqft: 7200,
    furnished: "Designer Furnished",
    fullAddress: "Frond G, Palm Jumeirah, Dubai",
    city: "Dubai",
    community: "Palm Jumeirah",
    agentName: "Ashish Lalwani",
    brokerName: "Vibgyor Real Estate",
    listingUrl: "#contact",
    listedDate: "2026-09-20",
  },
  {
    propertyId: "downtown-dubai-penthouse-1",
    title: "Burj Crown Sky Residence · Downtown Dubai",
    description: "Unobstructed Burj Khalifa views, double-height ceilings, concierge service.",
    propertyType: "Penthouse",
    offeringType: "forSale",
    price: 9200000,
    currency: "AED",
    bedrooms: 3,
    bathrooms: 4,
    areaSqft: 3100,
    furnished: "Unfurnished",
    fullAddress: "Downtown Dubai Boulevard, Dubai",
    city: "Dubai",
    community: "Downtown Dubai",
    agentName: "Ashish Lalwani",
    brokerName: "Vibgyor Real Estate",
    listingUrl: "#contact",
    listedDate: "2026-09-28",
  },
  {
    propertyId: "dubai-hills-golf-1",
    title: "Contemporary Golf Grove Residence · Dubai Hills Estate",
    description: "Expansive green views, family park adjoining, rooftop lounge.",
    propertyType: "Townhouse",
    offeringType: "forSale",
    price: 5400000,
    currency: "AED",
    bedrooms: 4,
    bathrooms: 4,
    areaSqft: 3350,
    furnished: "Unfurnished",
    fullAddress: "Dubai Hills Estate, Dubai",
    city: "Dubai",
    community: "Dubai Hills Estate",
    agentName: "Ashish Lalwani",
    brokerName: "Vibgyor Real Estate",
    listingUrl: "#contact",
    listedDate: "2026-09-10",
  },
  {
    propertyId: "business-bay-canal-1",
    title: "Waterfront Executive Suite · Business Bay",
    description: "Canal-front residence minutes from Downtown and DIFC financial hub.",
    propertyType: "Apartment",
    offeringType: "forSale",
    price: 2150000,
    currency: "AED",
    bedrooms: 2,
    bathrooms: 2,
    areaSqft: 1380,
    furnished: "Fully Furnished",
    fullAddress: "Marasi Drive, Business Bay, Dubai",
    city: "Dubai",
    community: "Business Bay",
    agentName: "Ashish Lalwani",
    brokerName: "Vibgyor Real Estate",
    listingUrl: "#contact",
    listedDate: "2026-10-01",
  },
  {
    propertyId: "jvc-smart-investment-1",
    title: "High-Yield Boutique Residence · Jumeirah Village Circle",
    description: "Smart home system, private plunge pool balcony, high rental yield track record.",
    propertyType: "Apartment",
    offeringType: "forSale",
    price: 1100000,
    currency: "AED",
    bedrooms: 1,
    bathrooms: 2,
    areaSqft: 860,
    furnished: "Fitted",
    fullAddress: "District 13, Jumeirah Village Circle, Dubai",
    city: "Dubai",
    community: "Jumeirah Village Circle",
    agentName: "Ashish Lalwani",
    brokerName: "Vibgyor Real Estate",
    listingUrl: "#contact",
    listedDate: "2026-09-25",
  },
  {
    propertyId: "abu-dhabi-yas-1",
    title: "Yas Island Water's Edge Residence · Abu Dhabi",
    description: "Promenade living on Yas Island, minutes from theme parks and Yas Mall.",
    propertyType: "Apartment",
    offeringType: "forSale",
    price: 1750000,
    currency: "AED",
    bedrooms: 2,
    bathrooms: 2,
    areaSqft: 1220,
    furnished: "Unfurnished",
    fullAddress: "Yas Island, Abu Dhabi",
    city: "Abu Dhabi",
    community: "Yas Island",
    agentName: "Ashish Lalwani",
    brokerName: "Vibgyor Real Estate",
    listingUrl: "#contact",
    listedDate: "2026-09-08",
  },
  {
    propertyId: "sharjah-al-jada-1",
    title: "Aljada Urban Living · Sharjah",
    description: "Modern contemporary urban living in Sharjah's prime destination.",
    propertyType: "Apartment",
    offeringType: "forSale",
    price: 890000,
    currency: "AED",
    bedrooms: 2,
    bathrooms: 2,
    areaSqft: 1050,
    furnished: "Unfurnished",
    fullAddress: "Muwaileh, Sharjah",
    city: "Sharjah",
    community: "Aljada",
    agentName: "Ashish Lalwani",
    brokerName: "Vibgyor Real Estate",
    listingUrl: "#contact",
    listedDate: "2026-09-12",
  },
];
